### ISSUE TITLE
Wrong guidelines for testing (naming conventions)

### ISSUE THREAD

**Issue by pirat89** [leapp-to/leapp-actors#69]
We should use unitary name for test files & it we shouldn't use the "test.py" name (see the [link](https://stackoverflow.com/questions/48719606/pytest-how-to-make-it-search-recursively)). In addition, [README](https://github.com/leapp-to/leapp-actors#naming-conventions) and [readthedocs](https://leapp.readthedocs.io/en/latest/unit-testing.html#getting-started-with-writing-tests) documentations are different. Both should be synced.

**Comment by pirat89** [comment]
We found issue with unitary names & pytest https://github.com/pytest-dev/pytest/issues/774

**Comment by vojtechsokol** [comment]
The naming of test files in the [README](https://github.com/leapp-to/leapp-actors#naming-conventions) is the correct one, see pytest's [naming conventions](https://docs.pytest.org/en/latest/goodpractices.html#conventions-for-python-test-discovery).

**Comment by examon** [comment]
This has been addressed in the https://github.com/leapp-to/leapp-actors/pull/74 and https://github.com/leapp-to/leapp/pull/341
