### ISSUE TITLE
make install-deps: missing dependencies for testing

### ISSUE THREAD

**Issue by pirat89** [leapp-to/leapp-actors#70]
There is not installed mock. Currently it is the only one dependency I found I missing here. But this one is not necessary in case you don't want to run tests.

**Comment by pirat89** [comment]
In case you would like to keep deps for testing separated, new target, e.g. `install-test-deps` would be still better than nothing. But probably it's not to big deal to keep this separated from normal deps now.

**Comment by artmello** [comment]
I may be wrong, but I am almost sure that python-mock was only used on the approach we proposed for mocking stored files. After hitting some issues (reported against leapp-to/leapp) we reverted that change and are not mocking files any more, and therefore not using python-mock. This, of course, do not invalidate the discussion about having a different rule to install test deps

**Comment by pirat89** [comment]
@artmello Ah, I thought it is planned to mock basically everything - variables, funktions, .... But that was just assumption maybe after I spend few previous weeks with mock in other projects.

We had short discussion with @shaded-enmity, that maybe would be better to modify guideline and/or change design of actor class so it would be possible to change "everything" in tests without need of mock. It will be discussed I guess in next week(s). As I realize now, there are already deps for pytest* so it's not only about the possible mock already.

**Comment by pirat89** [comment]
Fixed by PR #73
